In [1]:
import pandas as pd

In [2]:
Emp_List = ['abdul.bas@imerit.net', 'amirtha.m@imerit.net', 'arunprakash.b@imerit.net', 'charrukesi.s@imerit.net', 'dhivya.s@imerit.net', 'hariprasath.k@imerit.net', 'harshavardhini.h@imerit.net', 'jenipher.g@imerit.net', 'lakshminarayanan.s@imerit.net', 'logesh.g@imerit.net', 'madhumitha.sub@imerit.net', 'mahalakshmi.s@imerit.net', 'mangalanayaki.ms@imerit.net', 'mohana.s@imerit.net', 'naresh.kum@imerit.net', 'naveen.s1@imerit.net', 'praveen.a@imerit.net', 'priyadharshini.r@imerit.net', 'radhalakshmi.k@imerit.net', 'raguram.m@imerit.net', 'ramya.u@imerit.net', 'revathi.n@imerit.net', 'saravanan.n@imerit.net', 'shanmugapriya.s@imerit.net', 'suresh.m@imerit.net', 'suryaprakash.m@imerit.net', 'vidhya.k@imerit.net', 'vigneshwaran.s@imerit.net', 'vishnu.n1@imerit.net', 'yogesh.m@imerit.net', 'yuvashree.d@imerit.net', 'anusiya.j@imerit.net', 'chandru.s@imerit.net', 'divya.s1@imerit.net', 'karthi.n@imerit.net', 'kishore.aru@imerit.net', 'nivitha.g@imerit.net', 'ramsangari.san@imerit.net', 'sathish.s@imerit.net']

In [3]:
df = pd.read_csv(r"C:\Users\arun.prakash\Downloads\Vs Folders\Imerit_DW\Argus\Data\client_sheet\15-04-26_complete.csv")

In [9]:
Task_df = df.pivot_table(index='Last Labeler',aggfunc='count')['Task ID'].reset_index()

In [14]:
QC_df = df.pivot_table(index='Last Reviewer',aggfunc='count')['Task ID'].reset_index()

In [17]:
QC_df[~QC_df['Last Reviewer'].isin(Emp_List)]

               Last Reviewer  Task ID
4     brandonsim@invigilo.sg      671
5         brymol@invigilo.sg      604
10         eldon@invigilo.sg       13
13      jampel.ye@imerit.net     1056
15     julie.lodh@imerit.net       20
27    parthiban.s@imerit.net      421
35    samayeeta.s@imerit.net      124
39    subhojit.ga@imerit.net       91
40  suchaeeta.kar@imerit.net      533

In [12]:
Task_df[Task_df['Last Labeler'].isin(Emp_List)]

                     Last Labeler  Task ID
1            abdul.bas@imerit.net      778
2            amirtha.m@imerit.net      295
3            anusiya.j@imerit.net      216
5        arunprakash.b@imerit.net      116
7            chandru.s@imerit.net      205
8         charrukesi.s@imerit.net      301
9             dhivya.s@imerit.net      330
10            divya.s1@imerit.net      221
11       hariprasath.k@imerit.net      344
12    harshavardhini.h@imerit.net      608
14          jenipher.g@imerit.net      135
15            karthi.n@imerit.net      241
16         kishore.aru@imerit.net      124
17  lakshminarayanan.s@imerit.net      196
18            logesh.g@imerit.net      343
19      madhumitha.sub@imerit.net      368
20       mahalakshmi.s@imerit.net      536
21    mangalanayaki.ms@imerit.net      504
22            mohana.s@imerit.net      367
24          naresh.kum@imerit.net      230
25           naveen.s1@imerit.net      122
26           nivitha.g@imerit.net      195
28           praveen.a@imerit.net       64
29    priyadharshini.r@imerit.net      367
30      radhalakshmi.k@imerit.net      472
31           raguram.m@imerit.net      278
32      ramsangari.san@imerit.net      104
33             ramya.u@imerit.net      326
34           revathi.n@imerit.net      463
35         saravanan.n@imerit.net      100
36           sathish.s@imerit.net      236
37     shanmugapriya.s@imerit.net      652
39            suresh.m@imerit.net      175
40      suryaprakash.m@imerit.net      144
41            vidhya.k@imerit.net      689
42      vigneshwaran.s@imerit.net      109
43           vishnu.n1@imerit.net      409
44            yogesh.m@imerit.net      374
45         yuvashree.d@imerit.net      668

In [13]:
df.columns

Index(['Batch', 'External ID', 'Task ID', 'AngoHub URL', 'Asset's Stage',
       'Total Label Duration (sec)', 'Total Label Stage Visits',
       'Last Label Stage', 'Last Labeler', 'Total Review Duration (sec)',
       'Total Review Stage Visits', 'Last Review Stage', 'Last Reviewer',
       'Number of Classifications', 'Number of Tools',
       'Number of Tool Classifications', 'Number of Relations',
       'Number of Issues', 'Error Type: N/A', 'Error Code: N/A'],
      dtype='str')

In [20]:
df['Number of Tools'].sum()

np.int64(271554)