In [1]:
import pandas as pd

In [23]:
Emp_List = ['abdul.bas@imerit.net', 'amirtha.m@imerit.net', 'arunprakash.b@imerit.net', 'charrukesi.s@imerit.net', 'dhivya.s@imerit.net', 'hariprasath.k@imerit.net', 'harshavardhini.h@imerit.net', 'jenipher.g@imerit.net', 'lakshminarayanan.s@imerit.net', 'logesh.g@imerit.net', 'madhumitha.sub@imerit.net', 'mahalakshmi.s@imerit.net', 'mangalanayaki.ms@imerit.net', 'mohana.s@imerit.net', 'naresh.kum@imerit.net', 'naveen.s1@imerit.net', 'praveen.a@imerit.net', 'priyadharshini.r@imerit.net', 'radhalakshmi.k@imerit.net', 'raguram.m@imerit.net', 'ramya.u@imerit.net', 'revathi.n@imerit.net', 'saravanan.n@imerit.net', 'shanmugapriya.s@imerit.net', 'suresh.m@imerit.net', 'suryaprakash.m@imerit.net', 'vidhya.k@imerit.net', 'vigneshwaran.s@imerit.net', 'vishnu.n1@imerit.net', 'yogesh.m@imerit.net', 'yuvashree.d@imerit.net', 'anusiya.j@imerit.net', 'chandru.s@imerit.net', 'divya.s1@imerit.net', 'karthi.n@imerit.net', 'kishore.aru@imerit.net', 'nivitha.g@imerit.net', 'ramsangari.san@imerit.net', 'sathish.s@imerit.net']

In [7]:
Tracker_df =  pd.read_csv(r"C:\Users\arun.prakash\Downloads\Vs Folders\Imerit_DW\Argus\Data\client_sheet\Task Tracker - production_process.csv")

In [11]:
Traker_Task_ids = Tracker_df['Task ID'].dropna().to_list()

In [12]:
df = pd.read_csv(r"C:\Users\arun.prakash\Downloads\Vs Folders\Imerit_DW\Argus\Data\client_sheet\69c4dcbec37f2da518c9e238-export-2026-04-14_10-20-32_[TPT].csv")

In [13]:
df.head()

,Batch,External ID,Task ID,AngoHub URL,Asset's Stage,Total Label Duration (sec),Total Label Stage Visits,Last Label Stage,Last Labeler,Total Review Duration (sec),Total Review Stage Visits,Last Review Stage,Last Reviewer,Number of Classifications,Number of Tools,Number of Tool Classifications,Number of Relations,Number of Issues,Error Type: N/A,Error Code: N/A
0,Test,test-images-0193.png,69c53ad796749d3a00caa8c6,https://imerit.ango.ai/edit/69c53ad796749d3a00...,Review,46.41,1,Label,divya.s1@imerit.net,0.0,0,-,-,0,2,0,0,0,0,0
1,Test,test-images-0197.png,69c53ad796749d3a00caa8c7,https://imerit.ango.ai/edit/69c53ad796749d3a00...,Review,62.33,1,Label,naveen.s1@imerit.net,0.0,0,-,-,0,2,0,0,0,0,0
2,Test,test-images-0214.png,69c53ad796749d3a00caa8c8,https://imerit.ango.ai/edit/69c53ad796749d3a00...,Review,220.93,1,Label,karthi.n@imerit.net,0.0,0,-,-,0,20,0,0,0,0,0
3,Test,test-images-0215.png,69c53ad796749d3a00caa8c9,https://imerit.ango.ai/edit/69c53ad796749d3a00...,Review,694.78,1,Label,madhumitha.sub@imerit.net,0.0,0,-,-,0,20,0,0,0,0,0
4,Test,test-images-0278.png,69c53ad796749d3a00caa8ca,https://imerit.ango.ai/edit/69c53ad796749d3a00...,Review,125.74,1,Label,dhivya.s@imerit.net,0.0,0,-,-,0,3,0,0,0,0,0

In [24]:
Non_df = df[~df['Task ID'].isin(Traker_Task_ids)][['Last Labeler','Task ID']].reset_index()

In [36]:
df.groupby('Last Labeler')['Task ID'].count().reset_index()

                        Last Labeler  Task ID
0                                  -        1
1               abdul.bas@imerit.net      778
2               amirtha.m@imerit.net      295
3               anusiya.j@imerit.net      216
4         aravinthmadhu.p@imerit.net        2
5           arunprakash.b@imerit.net      115
6           balamurugan.r@imerit.net        3
7               chandru.s@imerit.net      205
8            charrukesi.s@imerit.net      301
9                dhivya.s@imerit.net      330
10               divya.s1@imerit.net      221
11          hariprasath.k@imerit.net      344
12       harshavardhini.h@imerit.net      608
13              jampel.ye@imerit.net        6
14             jenipher.g@imerit.net      135
15               karthi.n@imerit.net      241
16            kishore.aru@imerit.net      124
17     lakshminarayanan.s@imerit.net      196
18               logesh.g@imerit.net      343
19         madhumitha.sub@imerit.net      368
20          mahalakshmi.s@imerit.net      536
21       mangalanayaki.ms@imerit.net      504
22               mohana.s@imerit.net      367
23  nandeswar.a@imeritapprentice.net        2
24             naresh.kum@imerit.net      230
25              naveen.s1@imerit.net      122
26              nivitha.g@imerit.net      195
27            parthiban.s@imerit.net       46
28              praveen.a@imerit.net       64
29       priyadharshini.r@imerit.net      367
30         radhalakshmi.k@imerit.net      472
31              raguram.m@imerit.net      278
32         ramsangari.san@imerit.net      104
33                ramya.u@imerit.net      326
34              revathi.n@imerit.net      463
35            saravanan.n@imerit.net      100
36              sathish.s@imerit.net      236
37        shanmugapriya.s@imerit.net      652
38          suchaeeta.kar@imerit.net        1
39               suresh.m@imerit.net      175
40         suryaprakash.m@imerit.net      144
41               vidhya.k@imerit.net      689
42         vigneshwaran.s@imerit.net      109
43              vishnu.n1@imerit.net      409
44               yogesh.m@imerit.net      374
45            yuvashree.d@imerit.net      668

In [4]:
df.columns

Index(['Batch', 'External ID', 'Task ID', 'AngoHub URL', 'Asset's Stage',
       'Total Label Duration (sec)', 'Total Label Stage Visits',
       'Last Label Stage', 'Last Labeler', 'Total Review Duration (sec)',
       'Total Review Stage Visits', 'Last Review Stage', 'Last Reviewer',
       'Number of Classifications', 'Number of Tools',
       'Number of Tool Classifications', 'Number of Relations',
       'Number of Issues', 'Error Type: N/A', 'Error Code: N/A'],
      dtype='str')

In [32]:
df['Number of Tools'].sum()

np.int64(268159)

In [29]:
Non_df[Non_df['Last Labeler'].isin(Emp_List)].reset_index(drop=True)

    index                   Last Labeler                   Task ID
0     399           sathish.s@imerit.net  69c53ad796749d3a00caaa55
1    1047         yuvashree.d@imerit.net  69c53ad796749d3a00caacdd
2    1146       arunprakash.b@imerit.net  69c53ad796749d3a00caad40
3    1342       arunprakash.b@imerit.net  69c53ad896749d3a00caae04
4    1504      suryaprakash.m@imerit.net  69c53b0f2e0380af697b18be
5    1530           vishnu.n1@imerit.net  69c53b0f2e0380af697b18d8
6    1541     shanmugapriya.s@imerit.net  69c53b0f2e0380af697b18e3
7    4034           amirtha.m@imerit.net  69c5565948a08f92e908e0b7
8    7065            mohana.s@imerit.net  69c55812f702c081fa30cc2f
9    7209    harshavardhini.h@imerit.net  69c55812f702c081fa30ccbf
10   7566     shanmugapriya.s@imerit.net  69c55812f702c081fa30ce24
11   7773       hariprasath.k@imerit.net  69c55812f702c081fa30cef3
12   8087           revathi.n@imerit.net  69c55812f702c081fa30d02d
13   8325        charrukesi.s@imerit.net  69c55812f702c081fa30d11b
14   8354       hariprasath.k@imerit.net  69c55812f702c081fa30d138
15   8601            vidhya.k@imerit.net  69c55812f702c081fa30d22f
16   9129           revathi.n@imerit.net  69c5589725517a9975bca0c8
17   9326           vishnu.n1@imerit.net  69c5589725517a9975bca18d
18   9660           vishnu.n1@imerit.net  69c5589725517a9975bca2db
19   9802           nivitha.g@imerit.net  69c5589725517a9975bca369
20  10280       mahalakshmi.s@imerit.net  69c5589925517a9975bca547
21  10281           anusiya.j@imerit.net  69c5589925517a9975bca548
22  10323  lakshminarayanan.s@imerit.net  69c5589925517a9975bca572
23  10389      madhumitha.sub@imerit.net  69c5589925517a9975bca5b4
24  10501     shanmugapriya.s@imerit.net  69c5589925517a9975bca624
25  10782      ramsangari.san@imerit.net  69c559964bade8c68b20fa53
26  10790            vidhya.k@imerit.net  69c559964bade8c68b20fa5b
27  10922           sathish.s@imerit.net  69c559964bade8c68b20fadf
28  10980      radhalakshmi.k@imerit.net  69c559964bade8c68b20fb19
29  12064    mangalanayaki.ms@imerit.net  69c559964bade8c68b20ff55
30  12363            divya.s1@imerit.net  69c559964bade8c68b210080

In [30]:
Non_df[~Non_df['Last Labeler'].isin(Emp_List)].reset_index(drop=True)

    index                      Last Labeler                   Task ID
0       8        aravinthmadhu.p@imerit.net  69c53ad796749d3a00caa8ce
1     127        aravinthmadhu.p@imerit.net  69c53ad796749d3a00caa945
2     797  nandeswar.a@imeritapprentice.net  69c53ad796749d3a00caabe3
3     798          balamurugan.r@imerit.net  69c53ad796749d3a00caabe4
4     799          balamurugan.r@imerit.net  69c53ad796749d3a00caabe5
5     800  nandeswar.a@imeritapprentice.net  69c53ad796749d3a00caabe6
6     801          balamurugan.r@imerit.net  69c53ad796749d3a00caabe7
7     803              jampel.ye@imerit.net  69c53ad796749d3a00caabe9
8     804              jampel.ye@imerit.net  69c53ad796749d3a00caabea
9   10603            parthiban.s@imerit.net  69c559964bade8c68b20f9a0
10  12424            parthiban.s@imerit.net  69c559964bade8c68b2100bd
11  12450              jampel.ye@imerit.net  69c559964bade8c68b2100d7
12  12454              jampel.ye@imerit.net  69c559964bade8c68b2100db
13  12460            parthiban.s@imerit.net  69c559964bade8c68b2100e1